import type {ModelInput,ModelProvider,ModelResponse} from '../contracts/loop.js';
export interface OpenAICompatibleOptions {apiKey:string;model:string;endpoint:string;seatId?:string;pluginId?:string;pluginVersion?:string;temperature?:number}
export function createOpenAICompatibleModel(options:OpenAICompatibleOptions):ModelProvider {
 if(!options.apiKey||!options.model||!options.endpoint)throw new Error('Provider endpoint, model and API key are required');
 const endpoint=options.endpoint.replace(/\/$/,'')+'/chat/completions';
 const body=(input:ModelInput,stream=false)=>({model:options.model,messages:[{role:'system',content:input.systemPrompt},...input.history.map(message=>({role:message.role,content:typeof message.content==='string'?message.content:JSON.stringify(message.content)}))],...(input.tools.length?{tools:input.tools.map(name=>({type:'function',function:{name,description:name,parameters:{type:'object',additionalProperties:true}}}))}:{}),...(options.temperature===undefined?{}:{temperature:options.temperature}),...(stream?{stream:true}:{})});
 return {seatId:options.seatId??'model',pluginId:options.pluginId??'openai-compatible',pluginVersion:options.pluginVersion??'1',invoke:async(input,signal):Promise<ModelResponse>=>{
  const response=await fetch(endpoint,{method:'POST',signal,headers:{authorization:`Bearer ${options.apiKey}`,'content-type':'application/json'},body:JSON.stringify(body(input))});
  if(!response.ok)throw new Error(`Model provider HTTP ${response.status} ${response.statusText}: ${await response.text()}`);
  const data=await response.json() as {choices?:{message?:{content?:unknown;tool_calls?:{id?:string;function?:{name?:string;arguments?:string}}[]}}[];usage?:unknown};const message=data.choices?.[0]?.message;if(!message)throw new Error('Model provider returned no choice');
  const toolCalls=(message.tool_calls??[]).map(call=>{const fn=call.function;if(!call.id||!fn?.name)throw new Error('Model provider returned invalid tool call');return{id:call.id,name:fn.name,input:fn.arguments?JSON.parse(fn.arguments):{}}});return {content:message.content??'',toolCalls,...(data.usage===undefined?{}:{usage:data.usage})};
 },stream:async function*(input,signal){const response=await fetch(endpoint,{method:'POST',signal,headers:{authorization:`Bearer ${options.apiKey}`,'content-type':'application/json'},body:JSON.stringify(body(input,true))});if(!response.ok||!response.body)throw new Error(`Model provider HTTP ${response.status} ${response.statusText}: ${await response.text()}`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()??'';for(const line of lines){const text=line.trim();if(!text.startsWith('data:'))continue;const data=text.slice(5).trim();if(data==='[DONE]'){yield {done:true};return}const chunk=JSON.parse(data) as {choices?:{delta?:{content?:string}}[];usage?:unknown};const delta=chunk.choices?.[0]?.delta;yield {...(delta?.content===undefined?{}:{content:delta.content}),...(chunk.usage===undefined?{}:{usage:chunk.usage})};}}yield {done:true};}}
}

